### ISSUE TITLE
CNCjs not working at all. 

### ISSUE THREAD

**Issue by CorvoDewittV2** [jeffeb3/v1pi#26]
Hi I just set up Version 0.17, and Octoprint works fine, but CNCjs won't do anything. It connects, the console shows up after I select marlin and hit open, but it won't do anything. After about 2 minuets I get a pop up that says server has stopped working.  I will say it is my first rodeo with CNCjs but I have 2 printers running octoprint, so i kinda know my way around rpi but by no means an expert.

**Comment by jeffeb3** [comment]
Do you have the right port?

Have you disconnected from octoprint?

**Comment by CorvoDewittV2** [comment]
I was disconnected from octoprint, here is my order of operations:

Plug in pi and mpcnc
Wait 2 min to make sure everything is booted
Go to the server page 
Click on CNCjs
Connect using the only port listed, under marlin.
Console will pop up below the Connect tab
I can type commands into the console or press the move buttons but nothing happens (no ok's either)
2 min later the server crashes

**Comment by jeffeb3** [comment]
Which port and which pi?

ttyAMA0 is the onboard serial, and not the usb. I usually have two options if I have Marlin connected.

**Comment by CorvoDewittV2** [comment]
Oh huh ok I will have to check when I get home, I will report back with screenshots!

**Comment by CorvoDewittV2** [comment]
![image](https://user-images.githubusercontent.com/67569210/90696598-91375000-e24a-11ea-8140-075db40bed93.png)
![image](https://user-images.githubusercontent.com/67569210/90696666-ae6c1e80-e24a-11ea-88a3-e638025f2194.png)
This is as far as I get. After a little while it will just crash. It's actually not crashing right now...but still not moving the machine. Am I doing something dumb? I really hope I am doing something dumb.

**Comment by CorvoDewittV2** [comment]
WAIT I think I fixed it by changing the baud rate to 250000! Yeah it works now. Issue was between the keyboard and chair. :)

**Comment by jeffeb3** [comment]
Glad it's working for you. Those goofy utf characters are a good sign of bad baud rate.
