### ISSUE TITLE
Update CNCjs

### ISSUE THREAD

**Issue by aperoap** [jeffeb3/v1pi#5]
Hi, how can i update CNCjs?

**Comment by jeffeb3** [comment]
Sorry for not responding sooner. At any time, you can update the CNC.js installation using npm. 

1) Stop the service with `sudo service cncjs stop`
2) Upgrade with: `sudo npm install -g cncjs@latest –unsafe-perm`
3) Then reboot, and it should start up. Be patient, it will take a while on a pi.

I will also occasionally upgrade the whole image, which I'm in the process of doing right now, and I have a prerelease out with 0.9.20
