### ISSUE TITLE
Not working on RasPi4

### ISSUE THREAD

**Issue by richardvk** [jeffeb3/v1pi#9]
Hi, actually just want to confirm if anyone has tried the latest image on RasPi4? Its not working on mine, but runs fine when I transfer the same SD to a RasPi3. It this a Jessie vs Buster thing?

Just curious if its a known issue or just me :)

Happy to help build if required.

**Comment by jeffeb3** [comment]
Yeah, sorry. It's based on the raspian image before the 4 came out. I need to recut it with the 4 image.

**Comment by richardvk** [comment]
Thanks Jeff, all good. If you want me to help or test just shout :)

**Comment by jeffeb3** [comment]
I have a new image in the releases that is based on buster, so it works on a rpi4. It's still in "beta" or "RC".
